export const DEVYA_PARTY = {
  nameEn: 'Devya Solutions',
  nameAr: 'شركة ديفيا للحلول البرمجية',
  taglineEn: 'Software · Strategy · Systems',
  taglineAr: 'برمجيات · استراتيجية · أنظمة',
  addressEn: 'Cairo, Egypt',
  addressAr: 'القاهرة، جمهورية مصر العربية',
  email: 'contact@devya.dev',
  phone: '+20 102 467 2684',
  website: 'www.devya.dev',
  portfolio: 'https://www.devya.dev/portfolio',
  portfolioLabel: 'devya.dev/portfolio',
  booking: 'https://booking.devya-solutions.com',
  bookingLabel: 'booking.devya-solutions.com',
  quote: 'https://quote.devya-solutions.com',
  quoteLabel: 'quote.devya-solutions.com',
  representativeEn: 'Ahmed Mahmoud',
  representativeAr: 'أحمد محمود عيسوى',
  commercialRegister: '—',
  taxId: '—',
};
