export const DEVYA_PARTY = {
  nameEn: 'Devya Solutions',
  nameAr: 'شركة ديفيا للحلول البرمجية',
  taglineEn: 'Software · Strategy · Systems',
  taglineAr: 'برمجيات · استراتيجية · أنظمة',
  addressEn: 'Cairo, Egypt',
  addressAr: 'القاهرة، جمهورية مصر العربية',
  email: 'contact@devya.dev',
  phone: '+201055930032',
  website: 'www.devya.dev',
  portfolio: 'https://portfolio.devya.dev/',
  portfolioLabel: 'portfolio.devya.dev',
  booking: 'https://booking.devya.dev',
  bookingLabel: 'booking.devya.dev',
  quote: 'https://quote.devya.dev',
  quoteLabel: 'quote.devya.dev',
  representativeEn: 'Ahmed Mahmoud',
  representativeAr: 'أحمد محمود عيسوى',
  commercialRegister: '—',
  taxId: '—',
};
